[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
zora = "https://rpc.zora.energy"
zora_sepolia = "https://sepolia.rpc.zora.energy"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
